// apps/main-site/src/components/ProfileSetup.vue
<script setup lang="ts">
import { ref } from 'vue'
import { getToken, saveProfile, addChild, fetchUser, setUser, setChildPassword } from '@/api/auth'

const props = defineProps<{
  open: boolean
}>()

const emit = defineEmits<{
  complete: []
}>()

const step = ref(1)

// Step 1: Registrant info
const nickname = ref('')
const avatar = ref('')
const gender = ref('')
const birthday = ref('')

// Step 2: Children info
const children = ref([{ nickname: '', gender: '', birthday: '', avatar: '', phone: '', password: '' }])

const saving = ref(false)
const error = ref('')

const avatars = ['🦁', '🐯', '🐼', '🐨', '🐸', '🦊', '🐰', '🐙', '🦄', '🐲']

function updateChild(idx: number, field: string, value: string) {
  children.value[idx] = { ...children.value[idx], [field]: value }
}

function addNewChild() {
  children.value.push({ nickname: '', gender: '', birthday: '', avatar: '', phone: '', password: '' })
}

function removeChild(idx: number) {
  children.value = children.value.filter((_, i) => i !== idx)
}

async function save() {
  if (!nickname.value.trim()) {
    error.value = '请输入昵称'
    return
  }
  error.value = ''
  saving.value = true
  try {
    await saveProfile({
      nickname: nickname.value.trim(),
      avatar: avatar.value || undefined,
      gender: gender.value || undefined,
      birthday: birthday.value || undefined,
    })

    for (const child of children.value) {
      if (child.nickname.trim()) {
        const res = await addChild({
          nickname: child.nickname.trim(),
          gender: child.gender || undefined,
          birthday: child.birthday || undefined,
          avatar: child.avatar || undefined,
          phone: child.phone || undefined,
        })
        // Set independent password if provided
        if (child.password && res.code === 'OK') {
          await setChildPassword(res.data.id, child.password)
        }
      }
    }

    localStorage.removeItem('grandkidsgo_isNewUser')
    await fetchUser()
    emit('complete')
  } catch {
    error.value = '保存失败'
  } finally {
    saving.value = false
  }
}
</script>

<template>
  <div v-if="open" class="ps-overlay">
    <div class="ps-modal">
      <!-- Steps -->
      <div class="ps-steps">
        <div :class="['ps-step', { active: step >= 1 }]" />
        <div :class="['ps-step', { active: step >= 2 }]" />
      </div>

      <!-- Step 1: Registrant Profile -->
      <div v-if="step === 1">
        <h2 class="ps-title">欢迎加入童慧行</h2>
        <p class="ps-desc">请先填写注册人的信息</p>

        <div class="ps-section">
          <label class="ps-label">头像</label>
          <div class="ps-avatars">
            <button
              v-for="a in avatars"
              :key="a"
              :class="['ps-avatar', { selected: avatar === a }]"
              @click="avatar = a"
            >{{ a }}</button>
          </div>
        </div>

        <div class="ps-section">
          <label class="ps-label">昵称 <span class="ps-req">*</span></label>
          <input
            v-model="nickname"
            maxlength="20"
            placeholder="给自己取个好听的名字"
            class="ps-input"
          />
          <p class="ps-hint">例如：帅爸、美妈、童慧行家长</p>
        </div>

        <div class="ps-section">
          <label class="ps-label">性别</label>
          <select v-model="gender" class="ps-select">
            <option value="">保密</option>
            <option value="男">男</option>
            <option value="女">女</option>
          </select>
        </div>

        <div class="ps-section">
          <label class="ps-label">生日</label>
          <input v-model="birthday" type="date" class="ps-input" />
        </div>

        <p v-if="error" class="ps-error">{{ error }}</p>

        <button
          class="ps-btn ps-btn-primary"
          @click="step = 2"
        >下一步</button>
      </div>

      <!-- Step 2: Children Information -->
      <div v-if="step === 2">
        <h2 class="ps-title">添加孩子信息</h2>
        <p class="ps-desc">填写孩子信息，每个孩子将拥有独立的学习数据</p>

        <div class="ps-children">
          <div v-for="(child, i) in children" :key="i" class="ps-child-card">
            <button
              v-if="children.length > 1"
              class="ps-remove"
              @click="removeChild(i)"
            >✕</button>

            <div class="ps-section">
              <label class="ps-label-sm">头像</label>
              <div class="ps-avatars-sm">
                <button
                  v-for="a in avatars"
                  :key="a"
                  :class="['ps-avatar-sm', { selected: child.avatar === a }]"
                  @click="updateChild(i, 'avatar', a)"
                >{{ a }}</button>
              </div>
            </div>

            <div class="ps-child-field">
              <label class="ps-label-sm">孩子昵称</label>
              <input
                v-model="child.nickname"
                placeholder="如：小帅"
                class="ps-input"
              />
              <p class="ps-hint">不填可跳过</p>
            </div>
            <div class="ps-child-row">
              <div class="ps-child-field">
                <label class="ps-label-sm">性别</label>
                <select v-model="child.gender" class="ps-select">
                  <option value="">保密</option>
                  <option value="男">男孩</option>
                  <option value="女">女孩</option>
                </select>
              </div>
              <div class="ps-child-field">
                <label class="ps-label-sm">生日</label>
                <input v-model="child.birthday" type="date" class="ps-input" />
              </div>
            </div>
            <div class="ps-section" style="margin-top:8px">
              <label class="ps-label-sm">手机号（可选）</label>
              <input
                v-model="child.phone"
                placeholder="绑定后孩子可独立登录"
                class="ps-input"
                type="tel"
              />
            </div>
            <div class="ps-section">
              <label class="ps-label-sm">独立密码（可选）</label>
              <input
                v-model="child.password"
                placeholder="至少6位，孩子可用手机+密码登录"
                class="ps-input"
                type="password"
                minlength={6}
              />
            </div>
          </div>
        </div>

        <button class="ps-btn ps-btn-dashed" @click="addNewChild">
          + 添加另一个孩子
        </button>

        <p v-if="error" class="ps-error">{{ error }}</p>

        <div class="ps-actions">
          <button class="ps-btn ps-btn-ghost" @click="step = 1">上一步</button>
          <button
            class="ps-btn ps-btn-primary"
            :disabled="saving"
            @click="save"
          >{{ saving ? '保存中...' : '完成' }}</button>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.ps-overlay {
  position: fixed; inset: 0; z-index: 1000;
  display: flex; align-items: center; justify-content: center;
  background: rgba(0,0,0,0.5);
}
.ps-modal {
  background: white; border-radius: 16px;
  width: 100%; max-width: 448px; margin: 0 16px; padding: 32px;
  animation: fadeInUp 0.25s ease;
  max-height: 90vh; overflow-y: auto;
}
.ps-steps { display: flex; gap: 8px; margin-bottom: 24px; }
.ps-step {
  flex: 1; height: 8px; border-radius: 4px; background: #e5e7eb; transition: background 0.3s;
}
.ps-step.active { background: #3b82f6; }
.ps-title { font-size: 20px; font-weight: 700; color: #111827; margin-bottom: 4px; }
.ps-desc { font-size: 14px; color: #6b7280; margin-bottom: 24px; }
.ps-section { margin-bottom: 20px; }
.ps-label { display: block; font-size: 14px; font-weight: 500; color: #374151; margin-bottom: 8px; }
.ps-label-sm { display: block; font-size: 12px; color: #6b7280; margin-bottom: 4px; }
.ps-hint { font-size: 12px; color: #9ca3af; margin-top: 4px; }
.ps-req { color: #ef4444; }
.ps-avatars { display: flex; flex-wrap: wrap; gap: 8px; }
.ps-avatar {
  width: 48px; height: 48px; font-size: 24px;
  display: flex; align-items: center; justify-content: center;
  border-radius: 12px; border: 2px solid #e5e7eb;
  cursor: pointer; transition: all 0.2s;
}
.ps-avatar:hover { border-color: #9ca3af; }
.ps-avatar.selected { border-color: #3b82f6; background: #f0f9ff; transform: scale(1.1); }
.ps-avatars-sm { display: flex; gap: 4px; flex-wrap: wrap; margin-top: 4px; }
.ps-avatar-sm {
  width: 36px; height: 36px; font-size: 18px;
  display: flex; align-items: center; justify-content: center;
  border-radius: 8px; border: 2px solid #e5e7eb;
  cursor: pointer; transition: all 0.2s;
}
.ps-avatar-sm:hover { border-color: #9ca3af; }
.ps-avatar-sm.selected { border-color: #3b82f6; background: #f0f9ff; }
.ps-input {
  width: 100%; padding: 10px 12px; border: 1px solid #d1d5db;
  border-radius: 8px; font-size: 14px; outline: none; box-sizing: border-box;
}
.ps-input:focus { border-color: #3b82f6; box-shadow: 0 0 0 3px rgba(59,130,246,0.1); }
.ps-select {
  width: 100%; padding: 10px 12px; border: 1px solid #d1d5db;
  border-radius: 8px; font-size: 14px; outline: none; background: white;
}
.ps-error { color: #ef4444; font-size: 14px; margin-bottom: 16px; }
.ps-btn {
  width: 100%; padding: 12px; border-radius: 12px; font-size: 14px; font-weight: 500;
  border: none; cursor: pointer; transition: all 0.2s; font-family: inherit;
}
.ps-btn-primary { background: #2563eb; color: white; }
.ps-btn-primary:hover:not(:disabled) { background: #1d4ed8; }
.ps-btn-primary:disabled { opacity: 0.5; cursor: not-allowed; }
.ps-btn-dashed {
  width: 100%; padding: 10px; margin-top: 12px;
  border: 2px dashed #d1d5db; border-radius: 12px; background: transparent;
  color: #6b7280; font-size: 14px; cursor: pointer;
}
.ps-btn-dashed:hover { border-color: #3b82f6; color: #3b82f6; }
.ps-btn-ghost { background: #f3f4f6; color: #374151; }
.ps-btn-ghost:hover { background: #e5e7eb; }
.ps-children { max-height: 400px; overflow-y: auto; display: flex; flex-direction: column; gap: 16px; }
.ps-child-card {
  background: #f9fafb; border-radius: 12px; padding: 16px; position: relative;
}
.ps-remove {
  position: absolute; top: 8px; right: 8px; width: 24px; height: 24px;
  display: flex; align-items: center; justify-content: center;
  border: none; background: transparent; color: #9ca3af; cursor: pointer;
  font-size: 14px; border-radius: 50%;
}
.ps-remove:hover { background: #fef2f2; color: #ef4444; }
.ps-child-field { margin-bottom: 8px; flex: 1; }
.ps-child-row { display: flex; gap: 12px; }
.ps-actions { display: flex; gap: 12px; margin-top: 24px; }
.ps-actions .ps-btn { flex: 1; }

@keyframes fadeInUp {
  from { opacity: 0; transform: translateY(20px); }
  to { opacity: 1; transform: translateY(0); }
}
</style>

// apps/travel-guide/src/components/ProfileSetup.tsx
'use client';

import { useState } from 'react';
import { getToken } from '@/lib/auth';

type ProfileSetupProps = {
  open: boolean;
  onComplete: () => void;
};

const avatars = ['🦁', '🐯', '🐼', '🐨', '🐸', '🦊', '🐰', '🐙', '🦄', '🐲'];

export default function ProfileSetup({ open, onComplete }: ProfileSetupProps) {
  const [step, setStep] = useState(1);
  const [nickname, setNickname] = useState('');
  const [avatar, setAvatar] = useState('');
  const [children, setChildren] = useState([{ nickname: '', gender: '', age: '' }]);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');

  if (!open) return null;

  const updateChild = (idx: number, field: string, value: string) => {
    setChildren(prev => prev.map((c, i) => i === idx ? { ...c, [field]: value } : c));
  };

  const addChild = () => {
    setChildren(prev => [...prev, { nickname: '', gender: '', age: '' }]);
  };

  const removeChild = (idx: number) => {
    setChildren(prev => prev.filter((_, i) => i !== idx));
  };

  const saveProfile = async () => {
    if (!nickname.trim()) { setError('请输入昵称'); return; }
    setError('');
    setSaving(true);
    const token = getToken();
    try {
      await fetch('/api/user/profile', {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
        body: JSON.stringify({ nickname: nickname.trim(), avatar }),
      });

      for (const child of children) {
        if (child.nickname.trim()) {
          await fetch('/api/user/children', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
            body: JSON.stringify({
              nickname: child.nickname.trim(),
              gender: child.gender || undefined,
              age: child.age ? parseInt(child.age) : undefined,
            }),
          });
        }
      }

      localStorage.removeItem('grandkidsgo_isNewUser');
      onComplete();
    } catch { setError('保存失败'); }
    finally { setSaving(false); }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-md mx-4 p-8 animate-fadeInUp">
        {/* Steps indicator */}
        <div className="flex gap-2 mb-6">
          <div className={`h-2 flex-1 rounded-full ${step >= 1 ? 'bg-green-500' : 'bg-gray-200'}`} />
          <div className={`h-2 flex-1 rounded-full ${step >= 2 ? 'bg-green-500' : 'bg-gray-200'}`} />
        </div>

        {/* Step 1: Profile */}
        {step === 1 && (
          <>
            <h2 className="text-xl font-bold text-gray-900 mb-1">完善资料</h2>
            <p className="text-sm text-gray-500 mb-6">设置你的昵称和头像</p>

            <div className="mb-6">
              <label className="block text-sm font-medium text-gray-700 mb-2">选择头像</label>
              <div className="flex flex-wrap gap-2">
                {avatars.map(a => (
                  <button
                    key={a}
                    onClick={() => setAvatar(a)}
                    className={`w-12 h-12 text-2xl flex items-center justify-center rounded-xl border-2 transition-all ${
                      avatar === a ? 'border-green-500 bg-green-50 scale-110' : 'border-gray-200 hover:border-gray-300'
                    }`}
                  >
                    {a}
                  </button>
                ))}
              </div>
            </div>

            <div className="mb-6">
              <label className="block text-sm font-medium text-gray-700 mb-1">昵称 *</label>
              <input
                value={nickname}
                onChange={e => setNickname(e.target.value)}
                placeholder="给自己取个好听的名字"
                className="w-full px-3 py-2.5 border rounded-lg text-sm focus:ring-2 focus:ring-green-500 outline-none"
                maxLength={20}
              />
            </div>

            {error && <p className="text-sm text-red-500 mb-4">{error}</p>}

            <button
              onClick={() => { if (!nickname.trim()) { setError('请输入昵称'); return; } setError(''); setStep(2); }}
              className="w-full py-3 bg-green-600 text-white rounded-xl text-sm font-medium hover:bg-green-700 transition-all"
            >
              下一步
            </button>
          </>
        )}

        {/* Step 2: Children */}
        {step === 2 && (
          <>
            <h2 className="text-xl font-bold text-gray-900 mb-1">添加孩子信息</h2>
            <p className="text-sm text-gray-500 mb-6">填写孩子的昵称、性别和年龄（可跳过）</p>

            <div className="space-y-4 max-h-[300px] overflow-y-auto">
              {children.map((child, i) => (
                <div key={i} className="bg-gray-50 rounded-xl p-4 relative">
                  {children.length > 1 && (
                    <button
                      onClick={() => removeChild(i)}
                      className="absolute top-2 right-2 text-gray-400 hover:text-red-500 text-sm"
                    >
                      ✕
                    </button>
                  )}
                  <div className="space-y-3">
                    <div>
                      <label className="block text-xs text-gray-500 mb-1">孩子昵称</label>
                      <input
                        value={child.nickname}
                        onChange={e => updateChild(i, 'nickname', e.target.value)}
                        placeholder="如：小明"
                        className="w-full px-3 py-2 border rounded-lg text-sm focus:ring-2 focus:ring-green-500 outline-none"
                      />
                    </div>
                    <div className="flex gap-3">
                      <div className="flex-1">
                        <label className="block text-xs text-gray-500 mb-1">性别</label>
                        <select
                          value={child.gender}
                          onChange={e => updateChild(i, 'gender', e.target.value)}
                          className="w-full px-3 py-2 border rounded-lg text-sm focus:ring-2 focus:ring-green-500 outline-none"
                        >
                          <option value="">保密</option>
                          <option value="male">男孩</option>
                          <option value="girl">女孩</option>
                        </select>
                      </div>
                      <div className="flex-1">
                        <label className="block text-xs text-gray-500 mb-1">年龄</label>
                        <select
                          value={child.age}
                          onChange={e => updateChild(i, 'age', e.target.value)}
                          className="w-full px-3 py-2 border rounded-lg text-sm focus:ring-2 focus:ring-green-500 outline-none"
                        >
                          <option value="">请选择</option>
                          {Array.from({ length: 18 }, (_, i) => (
                            <option key={i + 1} value={i + 1}>{i + 1}岁</option>
                          ))}
                        </select>
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>

            <button
              onClick={addChild}
              className="w-full py-2.5 mt-3 border-2 border-dashed border-gray-300 rounded-xl text-sm text-gray-500 hover:border-green-300 hover:text-green-600 transition-colors"
            >
              + 添加另一个孩子
            </button>

            {error && <p className="text-sm text-red-500 mt-4">{error}</p>}

            <div className="flex gap-3 mt-6">
              <button
                onClick={() => setStep(1)}
                className="flex-1 py-3 bg-gray-100 text-gray-700 rounded-xl text-sm font-medium hover:bg-gray-200 transition-all"
              >
                上一步
              </button>
              <button
                onClick={saveProfile}
                disabled={saving}
                className="flex-1 py-3 bg-green-600 text-white rounded-xl text-sm font-medium hover:bg-green-700 disabled:opacity-50 transition-all"
              >
                {saving ? '保存中...' : '完成'}
              </button>
            </div>
          </>
        )}
      </div>
    </div>
  );
}
